kind: Service
apiVersion: v1
metadata:
  name: two-tier-service
  namespace: two-tier
spec:
  selector:
    app: two-tier
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
