kind: Service
apiVersion: v1
metadata:
  name: two-tier-svc
  namespace: two-tier
spec:
  selector:
    app: two-tier-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
